apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-certs
  namespace: argocd
spec:
  secretName: argocd-server-tls
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
    - argocd.robotcocktail.ovh
  #ipAddresses: # letsencrypt will not issue certs for a private IP address
  #  - x.x.x.x
  # Issuer references are always required.
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    #group: cert-manager.io
