apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-webhook-ovh:secret-reader
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["ovh-credentials"]
    verbs: ["get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-webhook-ovh:secret-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-webhook-ovh:secret-reader
subjects:
  - apiGroup: ""
    namespace: default
    kind: ServiceAccount
    name: cert-manager-webhook-ovh
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns-ovh
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: victor.talpaert@gmail.com
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
      - dns01:
          cnameStrategy: Follow
          webhook:
            groupName: robotcocktail.ovh
            solverName: ovh
            config:
              endpoint: ovh-eu
              applicationKeyRef:
                key: applicationKey
                name: ovh-credentials
              applicationSecretRef:
                key: applicationSecret
                name: ovh-credentials
              consumerKeyRef:
                key: consumerKey
                name: ovh-credentials
