apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-webhook-ovh
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  source:
    chart: cert-manager-webhook-ovh
    repoURL: https://aureq.github.io/cert-manager-webhook-ovh/
    targetRevision: 0.7.0
    helm:
      valuesObject:
        # The GroupName here is used to identify your company or business unit that
        # created this webhook.
        # For example, this may be "acme.mycompany.example".
        # This name will need to be referenced in each Issuer's `webhook` stanza to
        # inform cert-manager of where to send ChallengePayload resources in order to
        # solve the DNS01 challenge.
        # This group name should be **unique**, hence using your own company's domain
        # here is recommended.
        groupName: robotcocktail.ovh
